In [4]:
import numpy as np

In [13]:
def getMinorMatrix(A,j,i):
    n =len(A)
    M = np.zeros((n-1,n-1))
    for a in range(0,n-1):
        k = a if (a<i) else a+1
        for b in range(0,n-1):
            l = b if (b<j) else b+1
            M[a,b] = A[k,l]
    return M

In [30]:
def determinant(M):
    if len(M) ==2:
        return M[0,0]*M[1,1]-M[0,1]*M[1,0]
    detval =0
    for c in range(len(M)):
        detval += ((-1)**c)*M[0,c]*det(getMinorMatrix(M,0,c))
    return detval

In [31]:
#2 -(a)
A = np.array([[2,1],[4,5]])
print("det(A) = ",determinant(A))

det(A) =  6


In [32]:
#2-(b)
B = np.array([[4,3],[1,7]])
print("det(B) = ",determinant(B))

det(B) =  25


In [49]:
#3-(A)
C = np.array([[5,2,3],[3,-1,1],[6,4,2]])
det_c = "det(C) = {:.1f}".format(np.linalg.det(C))
print(det_c)

det(C) = 24.0


In [51]:
#3-(B)
D = np.array([[3,2,3],[6,1,2],[1,2,5]])
det_d = "det(C) = {:.1f}".format(np.linalg.det(D))
print(det_d)

det(C) = -20.0


In [56]:
#7-(a)
A =np.array([[1,5,-6],[-1,-4,4],[-2,-7,9]])
det_a = "det(A) = {:.1f}".format(np.linalg.det(A))
print(det_a)

det(A) = 3.0


In [58]:
#8-(a)
A = np.array([[1,3,0,2],[-2,-5,7,4],[3,5,2,1],[1,-1,2,-3]])
det_a = "det(A) = {:.1f}".format(np.linalg.det(A))
print(det_a)

det(A) = -0.0


In [60]:
#19-(c)
C = np.array([[5,6,0,0],[3,7,0,0],[1,2,2,1],[3,1,3,7]])
det_c = "det(C) = {:.1f}".format(np.linalg.det(C))
print(det_c)

det(C) = 187.0


In [67]:
from numpy.linalg import inv
a=np.array([[2,5,5],[-1,-1,0],[2,4,3]])
ainv = inv(a)
print(ainv)

[[ 3. -5. -5.]
 [-3.  4.  5.]
 [ 2. -2. -3.]]
