In [1]:
import numpy as np

## Q.6 -(a)


In [4]:
A = np.array([[0,-1],[-2,-3]])
w,v = np.linalg.eig(A)
print(w)
print(v)

[ 0.56155281 -3.56155281]
[[ 0.87192821  0.27032301]
 [-0.48963374  0.96276969]]


## Q.6-(b)

In [6]:
B = np.array([[1,-1],[2,4]])
w1,v1 = np.linalg.eig(B)
print(w1)
print(v1)

[2. 3.]
[[-0.70710678  0.4472136 ]
 [ 0.70710678 -0.89442719]]


## Q.6-(C)

In [9]:
C = np.array([[1,2,2],[0,2,1],[-1,2,2]])
w2,v2 = np.linalg.eig(B)
print(w2)
print(v2)

[2. 3.]
[[-0.70710678  0.4472136 ]
 [ 0.70710678 -0.89442719]]


## Q.6-(D)

In [11]:
D = np.array([[1,0,-1],[1,2,1],[2,2,3]])
w3,v3 = np.linalg.eig(D)
print(w3)
print(v3)

[2. 3. 1.]
[[-6.66666667e-01 -4.08248290e-01  7.07106781e-01]
 [ 3.33333333e-01  4.08248290e-01 -7.07106781e-01]
 [ 6.66666667e-01  8.16496581e-01  1.75541673e-16]]


## Q.6-(E)

In [12]:
E = np.array([[1,-3,3],[3,-5,3],[6,-6,4]])
w4,v4 = np.linalg.eig(E)
print(w4)
print(v4)

[ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]
[[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]


## Q.6-(F)

In [13]:
F = np.array([[1,-1,0],[-1,2,-1],[0,-1,1]])
w5,v5 = np.linalg.eig(E)
print(w5)
print(v5)

[ 4.+0.00000000e+00j -2.+1.10465796e-15j -2.-1.10465796e-15j]
[[-0.40824829+0.j          0.24400118-0.40702229j  0.24400118+0.40702229j]
 [-0.40824829+0.j         -0.41621909-0.40702229j -0.41621909+0.40702229j]
 [-0.81649658+0.j         -0.66022027+0.j         -0.66022027-0.j        ]]
