In [4]:
import numpy as np

In [5]:
#행렬 에 필요한 벡터들 생성
print("벡터의 결합에 의한 행렬 생성")
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
v3 = np.array([7,8,9])

벡터의 결합에 의한 행렬 생성


In [6]:
#v1 v2 v3를 행으로 하는 행렬A생성
A = np.vstack([v1,v2,v3])
print("A=",A)

A= [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
# v1 v2 v3를 열로 하는 행렬B생성
B = np.column_stack([v1,v2,v3])
print("B=",B)

B= [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [8]:
#행렬C생성
C = np.array([[1,2],[3,4],[5,6]])
print("C= ",C)

C=  [[1 2]
 [3 4]
 [5 6]]


In [10]:
#C에 v3를 열로 추가하여 D 생성
D = np.column_stack([C,v3])
print("D= ",D)

D=  [[1 2 7]
 [3 4 8]
 [5 6 9]]


In [11]:
print("행렬의 성분 접근")
E = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

행렬의 성분 접근


In [13]:
print("E[0,3] =",E[0,3]) #1row 4column
print("E[1,2] =",E[1,2]) #2row 3column

E[0,3] = 4
E[1,2] = 7


In [16]:
print("E[0:2,2] =",E[0:2,2]) #E의 1~2행 3열에 해당하는 부분행렬
print("E[0:2, 2:4] =",E[0:2, 2:4]) #E의 1~2행 3~4열에 해당하는 부분행렬
print("E[2,:]=",E[2,:]) #E의 3행에 해당하는 부분행렬

E[0:2,2] = [3 7]
E[0:2, 2:4] = [[3 4]
 [7 8]]
E[2,:]= [ 9 10 11 12]


In [17]:
print("성분의 변경")
print("E= ",E)

성분의 변경
E=  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
#E의 1행 1열 성분을 -1로 변경
print("E[0,0] = ",E[0,0])
E[0,0] = -1
print(E)
print("E[0,0]=",E[0,0])

E[0,0] =  1
[[-1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
E[0,0]= -1
