#linear_algebra 08

In [1]:
import numpy as np

## Question 40

In [2]:
# Q.40

#40-1
u1 = np.array([2,-1,4])
v1 = np.array([-1,2,5])
a1 = np.cross(u1,v1)
print(a1)

#40-2
u2 = np.array([-1,2,5])
v2 = np.array([2,-1,4])
a2 = np.cross(u2,v2)
print(a2)

#40-3
u3 = np.array([0,0,0])
v3 = np.array([1,2,1])
a3 = np.cross(u3,v3)
print(a3)

#40-4
u4 = np.array([2,1,-1])
v4 = np.array([-1,2,-2])
a4 = np.cross(u4,v4)
print(a4)


[-13 -14   3]
[13 14 -3]
[0 0 0]
[0 5 5]


## Question 44번


In [3]:
#Q.44
O = np.array([0,0,0])
A = np.array([1,1,0])
B = np.array([0,1,1])
C = np.array([1,2,1])

OA = O - A
OB = O - B
Cross = np.cross(OA,OB)
norm = np.linalg.norm(Cross)
print(norm)

1.7320508075688772


## Question 45번

In [4]:
#Q,45
O = np.array([0,0,0])
A = np.array([4,2,1])
B = np.array([1,3,2])
C = np.array([2,2,5])

OA = A - O
OB = B - O
OC = C - O

cross = np.cross(OB,OC)
nrom = np.linalg.norm(cross)
norm = np.cross(OA,cross)
n = np.linalg.norm(norm)
print(n)

a = np.linalg.det([[4,2,1],[1,3,2],[2,2,5]])
print(a)

38.13135192987524
37.99999999999999


## Question 47번

In [5]:
#Q.47
#47-1
a = np.linalg.det([[2,0,3],[0,6,2],[3,3,0]])
print("(A):",a)
#47-2
b = np.linalg.det([[1,1,0],[-1,0,1],[2,3,4]])
print("(B):",b)
#47-3
c = np.linalg.det([[0,1,1],[1,2,3],[0,0,0]])
print("(C):",c)
#47-4
d = np.linalg.det([[0,0,0],[1,2,3],[2,3,4]])
print("(D):",d)

(A): -65.99999999999997
(B): 2.9999999999999996
(C): 0.0
(D): 0.0
